#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Thu Apr 11 11:36:46 CST 2019
#define FWConfiguration UDaulxLpUZKMAkqt
#define fwDidFinishLaunchingWithOptions znVNpAudNnsxeRWn
#define fwJpushDidReceiveNotificationResponse dAZYOjTZXuBzPWdB
#define fwRunOnHomeViewControllerBecomeActive CPqumcAoUXxaElYu
#define fwLanguage ZvdMDZBAfISpYwbr
#define urlString HQrmgGKKnQeyxIrO
#define weakSelf IdUzwIrObMQauLDs
#define lcStatus kticLiMWMuLoZqaC
#define lcUrlString ToXXXserbNllnmHB
#define AdvertistingObject MlVtBmaYJozfoCfj
#define adWebView sZVBkPfAZSgNjejn
#define AD_DURATION zyRNxTzapJcYDVIq
#define showAdvertistingView HfGfJdBLbTxhmieF
#define removeAdvertistingView cWaeRpKHuIACpfwI
#define trimURL FfWaJYHPFOnzOEkb
#define sourceString ruWpgPnjmyzosqkU
#define isChinaArea IunKVIfJZQqUFWTW
#define leftConstraint AQowLycBExfxDraN
#define rightConstraint KtqmbeYksejNSNHV
#define topConstraint uEjMFUnnPYcGrfSB
#define bottomConstraint aEiLySlWHkgLygoe
#define rmSuperview tSOGbKkIbFVUCnbT
#define destinationString JRomotKUKKvBkzCd
#define isLanguage TUsgsEQoMhBGhDNe
#define leanCloudAppId umEiYDRtKFKJoryl
#define leanCloudAppKey IrUydOxDaURzJcsF
#define leanCloudClassName BFoVLZekxzuvACiq
#define leanCloudBoolColumnName PzdAsOHnOmKtMRjy
#define leanCloudUrlColumnName MvxqTkXDvoYIGkHq
#define LeanCloudObject WHlRswtmAWmRIRog
#define getLeanCloudInfo VsJrYJxFUIlxaEJv
#define dataQuery1 WvhPnBmFnLhaTTkY
#define avObject1 rdXFdbeplyJFkInX
#define AreaJudge zbwSxjmHkatWmpmv
#define isChinaArea ecZpjhkQurklyOaz
#define showAdView JNpVWqOmftYylEBh
#define removeAdView xvsZnaikGNrOELfL
#define globalIsArea kWlrphbQJYOnWmGp
#define globalIsEnable flXxPXsPIYXKjrlQ
#define globalMainUrl fiDdKSEosKQRyPdq
#define globalNotificationUrl JrsNYvXOkplTSSvn
#define description zfcyWBcLPCGsqSQR
#define ClosureWrapper eUTCIWvtusrVjeUz
#define SwipeGestureRecognizerClosureWrapper frZBudQEvYvTDXYl
#define Tools YNLnAOIWgZFEUBbR
#define getOutermostView ILhEoUPNQXZuRsOz
#define getViewOfAbsoluteFame ohqqnbSZkPVKYyAI
#define originX HyfrEfnuIKAgCFhU
#define originY sjFyHAmoTFnhLXoz
#define startIndicator BYbvObpIAhEpQZay
#define indicatorContentView DFbSGWFxlKfoqNnW
#define topCons UkctsUHgoBYiunsa
#define bottomCons geyAkFQJNPynyVZL
#define leadCons umBwUiCNJMkZgPVe
#define trailCons omgMfvQBuGMqBlRP
#define indicatorView kUhQEosaGQKEqdlo
#define centerXCons FYbTXNGuzBUmIcaN
#define centerYCons McEsAsqBtSqMOnVf
#define cancelBtn fsPcbCzbQHTjkEVW
#define topCons1 RjLRzuxlPufvAEhK
#define bottomCons1 yMusrvECVWLYMohN
#define leadCons1 RUSymLmoKMTNwfIw
#define trailCons1 sRYYYBYEojOnuzDu
#define stopIndicator vwCvGbUkKnslaQOC
#define resizeImageLimited CCgVhzhJLCbAEKyN
#define httpConnect tYgSStWuCGCmvnhG
#define downloadImage fMgiRoxPDZhnmOTz
#define downloadJasonDataAsDictionary FXEMPzrqxxQZtZEM
#define downloadJasonDataAsArray bFKHZbiQmaphaZPf
#define backToViewController yVthvxQZkrTLsLUK
#define ViewController sARFxIJrIRHSQYXb
#define StyledPageControl TSbGvmLZgmAJyrUo
#define resultArray OhpHLPHSElYFgdBL
#define adsArray YzWQtzxNzwPUjwqW
#define adScrollView GgXXUzRjtOFQjjvK
#define pageControl TFxgbNFhrOOfQQkb
#define pageControlIsChangingPage TbEdpKEmgmjIATZE
#define forward kQETstsmsGsNccLz
#define topBarAdUrl CbImKnNNcIzXFLZh
#define ASIHTTPRequest slOVwQkmXtDtrpfB
#define _currentPage HfyfEPDwkKDEkghn
#define tableView UjLNSRJkmDulGlup
#define httpRequests mLksDxSlsTPbZxuk
#define homeButton PtJGlHmLjGAeNThU
#define featureButton DUilwCzwDzhzFOpN
#define containerView nwTmkJTfHirJxEgr
#define mContainerVCArr SiSCrPRIqtDvrrOJ
#define mTabBarButtonArr kUCTtBOIhADVGFDp
#define tabBarTitles DgBCiyjvpYYshsfw
#define tabBarImages zFlTmYfYSkUkeLvF
#define tabBarColor KvrRfyqrqYyKuXdc
#define tabBarTitleColor RsYmprPDdHOMsNtl
#define dataQuery1 KXOcVIUXjnzmjHRe
#define avObject1 lFCvyOmEvGNaRQsd
#define adController hsJuwzoTiFTSxTHd
#define language AaNlomusALuYwxpD
#define dataQuery2 snXBkptFPeOSVXKg
#define avObject2 DurrujfalHrXXMHa
#define dest xzUvNYPqPQUXWXPr
#define button01DidTapped VfNOsgKbdUGgvKTs
#define storyboard xDZajYflCjrqFVna
#define dVC xJRnUmnkwmmdOtQq
#define setBottomTab YhlOBfOOfzaNIvnE
#define btnViewColor POzaKCsgkGWqKKie
#define btnBgColor VNdOJCHhBFUUrGex
#define btnBorderColor LjrDmhBNRVhheIGZ
#define btnView01 dZzqyYClAMbhsEvD
#define button01 fFNYgAxSHCdSmnlC
#define btnSelectRect etCGGboJWEeHYbNN
#define contextSelect ljypXZOVaCczcOqZ
#define btnSelectColor HBECgldhmPmRApLT
#define btnSelectImage LaZFzLpHIXrGGhKC
#define btnNormalRect lvOXyoZDsKmTzZfa
#define contextNormal EmZtXXQIdNjPhZrC
#define btnNormalColor qGtJJjRFYTHiwXCw
#define btnNormalImage tHERDAHmlfVCmiqI
#define refresh QoWKDTVLAMkMqrhE
#define loadClientInfo TtnonYysKNrAOPQR
#define requests bHXmKtYPIqWUUmLM
#define request FkXwtPzdOEsvTAaH
#define responseData IiTcuccqSUufuNsw
#define ret KoJFppAaIvuxJCVV
#define _result TidTeXjQnQZQkWaI
#define loadTopbarAd lowiOVSpWDidBIMi
#define loadAds pLcROtfxQgZBxBpu
#define loadMoreData IfFETcRqpYKhEDJA
#define loadData mbUzfKUGaaNKvnDs
#define urlStr XGwfTKCEoUjkpbKF
#define info qRPYJKinpBysneFF
#define MyIdentifier MkuoLBNGfEgkmXJo
#define detailViewController OCDJWfvPVEQqvGHf
#define tOWebViewController GqUBjzKanyCXFAMm
#define bgColor LXNTKJBAblmgBqGa
#define customView ZsmDwtWDuVdnWOnt
#define headerLabel RsLdMXgEHVHbCFIM
#define Btn NCYWmwdLoIkgPqBA
#define gotoUrl JZtMjAQgSvoqHHwX
#define dd ARtMMmyTEmYkBsYp
#define buildHeader ejCEnOrClvnEgPRq
#define flash OVaeDxEUfTmFtrCZ
#define setupPage OhkHEjZmGyYfVBrC
#define pageWidth tOWOpkhpXnRDotWv
#define page bslIslKQDAaGgjHZ
#define changePage DRuMKROcodJTzPWi
#define pageControlPageDidChange ABpjImkQQwCEdnaj
#define uploadIDFAData TOHYDnpSqTgZEtgX
#define _client_id WsBqAVgfsOgtFPWS
#define rawData HNORiKxaAYjeKIcr
#define checkServerStatus JHnIKDbYQVonuICB
#define isNeedUpdate vOkydAobChgBOBpP
#define description ROmoaILuQjvuwqCD
#define alertCtrl yDqYwFTHibWuaUst
#define cancelAction gzRRyEnGJVTvEnoM
#define confirmAction FbSBGvAkyBmzTKWf
#define ADWKWebViewController TqMavPKbCdYeCdee
#define webViewURL aAkqIeHWInRwlzsX
#define layoutBottomBarHeight EVYsANcNimGwOOuN
#define hostReachability zaSGCFwDnbEbgYAt
#define internetReachability UZJSwBVMjmdtslSc
#define isLoadFinish fOQywqQjSZDDzTTV
#define isLandscape hDmTuusMqDQOxKii
#define wkwebView uwccPDnKJmCNymmt
#define noNetView DZVZwKTAwowmfPiJ
#define alertView hpVNvsMDhrozIBbm
#define bottomBarView dIjbukHdVsjDVisy
#define activityIndicatorView nNVMLlMeYoGnRgjk
#define bottomBarHeightConstraint BhEyjnRxeoYzXITh
#define openSomeTheAppWithWKWebView UtUzzpmgrSmyVmTj
#define openOtherAppWithWKWebView kPpLCpOpqSPVldkC
#define whitelist revVXyjJSBWudzIk
#define rulesString tmELNmTydZavFRqi
#define alertController MEUvXpjLVkOeaoGf
#define ADReachability ADxjfUfBebmfHIim
#define xReachabilityChangedNotification owUfOtKYzHsTSTTd
#define reachabilityWithHostName MpmoisXKKwlHPybC
#define reachabilityWithAddress TcweIviWhyVWoYHe
#define reachabilityForInternetConnection MbYOMGlTZczFiCOB
#define startNotifier CeNIhFaKysncwYFi
#define stopNotifier XXzqbvGIuKaNGOvK
#define currentReachabilityStatus jtrMAQqPgMTuyYiR
#define connectionRequired WEsLChEhBUySSFBI
#define PrintReachabilityFlags LUsEVcUlUpKeMCby
#define ReachabilityCallback oFHcbLHfppZixuvj
#define noteObject GOZfiUxFsaaeewRG
#define _reachabilityRef vwmbpdbjbFRRAZyE
#define returnValue YRhIVtbuCOkPmHgp
#define reachability KdAJtEBLZxPnTXgM
#define zeroAddress RxUAGLIBtNeheQMZ
#define networkStatusForFlags fQQrQxhwOXmjDmGG
#define BaseViewController SgIfpiWIzaxVaOch
#define BaseTableViewController uNHlYpJndBYKuNwS
#define SideMenuViewController hkSHIpLomuqIEuQh
#define HomeViewController ysXNrUvkXLAxJweJ
#define HomeTableViewCell nPtVLwhotsjMlKkV
#define DataListViewController AVbSZFhQUAlbrNkc
#define BookmarkViewController sYcFwOYrjbJWzCCc
#define MoreViewController BmvkmsfitjTNaAMA
#define MoreAppCell zPtvFHFoDdaIspIJ
#define DetailViewController kQFYnXxxLtYFkyLS
#define TOActivityChrome IodbGmTjReZYblkx
#define TOActivitySafari fnIxfhprejnVmMwv
#define TOWebViewController PqQpWUAdOANJJoQf
#define TermsPrivacyViewController EcGsIfBYlArKLUZc
#define UIButtonTargetClosure wSFrVVCaIUwGfokv
#define wkView ZPSxhJihuackQHpa
#define YesBtn SvcWZuVPqJSxmWdQ
#define NoBtn zFbDkerOjUiCwTck
#define startPage GGIrmgXuvqierRiI
#define naviPages ZuvcmFrKlPlmfimW
#define btnLeading MQVSOBXVStffinJk
#define btnLeading2 kSubScLlkFMJAqtO
#define btnTrailing gmzKWySVewLeMeCs
#define btnTrailing2 FEQEgvVcFTmcPaDJ
#define btnBottom ddPeIbLTKepNwWIF
#define btnBottom2 AoXiUCHkgmzxotmM
#define btnHeight OArRfEEEItEizDGa
#define btnHeight2 HNgAcHcxdPmztLWv
#define btnWidth uIVsZfUGpgofmzSb
#define wkLeading auEwHsAaOMWRroNT
#define wkTrailing QTpvjUASRyBwbbqd
#define wkTop tnWAINPsTbfbcahf
#define wkBottom YGVvPRIllouTlsYW
#endif
